function [fitresult, gof] = createYCFit(Life, Yield)
%CREATEFIT(LIFE,YIELD)
%  Create a fit.
%
%  Data for 'Svensson Fit' fit:
%      X Input : Life
%      Y Output: Yield
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 25-Oct-2011 08:43:26


%% Fit: 'Svensson Fit'.
[xData, yData] = prepareCurveData( Life, Yield );

% Set up fittype and options.
ft = fittype( 'b0+b1*exp(-x/t1)+b2*(-x/t1).*exp(-x/t1)+b3*(x/t2).*exp(-x/t2)', 'independent', 'x', 'dependent', 'y' );

opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf -Inf -Inf 0 0];
% opts.StartPoint = [0.0357116785741896 0.849129305868777 0.933993247757551 0.678735154857773 0.757740130578333 0.743132468124916];
opts.StartPoint = [0.5 0.849129305868777 0.933993247757551 0.678735154857773 0.757740130578333 0.743132468124916];

opts.Upper = [Inf Inf Inf Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );


